daemon off;
pid @PREFIX@/nginx.pid;
error_log @PREFIX@/logs/error.log info;
worker_processes 1;
events { worker_connections 128; }
http {
    server {
        listen 127.0.0.1:@PORT@;
        location / { return 200 "OK\n"; }
    }
}
