@LOAD@
daemon off;
pid @PREFIX@/nginx.pid;
error_log @PREFIX@/logs/error.log info;
worker_processes 1;
events { worker_connections 10; }
http {
    @PROBE_ZONE@
    server {
        listen 127.0.0.1:@PORT@;
        location / { return 200 "main request\n"; }
        location /auth { return 200 "auth subrequest\n"; }
        location /__probe { @PROBE@ }
    }
}
